[package]
name = "bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
ethers = { workspace = true }
bridge-config = { workspace = true }